# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edlibalign <- function(query, target, input_mode, input_task, k, cigar_format, input_additionalEqualities = NULL) {
    .Call('_edlibR_edlibalign', PACKAGE = 'edlibR', query, target, input_mode, input_task, k, cigar_format, input_additionalEqualities)
}

